################################################################
################        2675 linhas de codigo    ###############
################################################################

Traceback (most recent call last):
  File "Interface.py", line 250, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 28, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 182, in salvar
    self.statusFile.push(contexto,str(dialog.get_filename()))
NameError: global name 'dialog' is not defined
Traceback (most recent call last):
  File "Interface.py", line 175, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 175, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 175, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.statusFile.push(contexto,str(self.dialog.get_filename()))
AttributeError: 'NoneType' object has no attribute 'get_filename'
Traceback (most recent call last):
  File "Interface.py", line 174, in salvar
    self.dialog.destroy()
AttributeError: 'NoneType' object has no attribute 'destroy'
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 401, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "Interface.py", line 401, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 270, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 79, in treinar
    self.net.trainf = neurolab.train.train_rprop
AttributeError: 'NoneType' object has no attribute 'trainf'
Traceback (most recent call last):
  File "Interface.py", line 228, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 410, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
AttributeError: 'NoneType' object has no attribute 'sim'
Traceback (most recent call last):
  File "Interface.py", line 228, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 309, in tratarEntrada
    novaf = self.extrair_dados(caminho)
  File "Interface.py", line 327, in extrair_dados
    data = get_data(caminho)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_ods/__init__.py", line 344, in get_data
    return read_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 311, in get_data
    data = load_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 176, in load_data
    filename))
NotImplementedError: Cannot read content of file type png from file /home/targueriano/neuroIFC/neuro.png
Traceback (most recent call last):
  File "Interface.py", line 309, in tratarEntrada
    novaf = self.extrair_dados(caminho)
  File "Interface.py", line 327, in extrair_dados
    data = get_data(caminho)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_ods/__init__.py", line 344, in get_data
    return read_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 311, in get_data
    data = load_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 176, in load_data
    filename))
NotImplementedError: Cannot read content of file type png from file /home/targueriano/neuroIFC/neuro.png
Traceback (most recent call last):
  File "Interface.py", line 227, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 254, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 25, in treinar
    self.errors = self.net.train(self.inputs, self.targets,
AttributeError: 'NoneType' object has no attribute 'train'
Traceback (most recent call last):
  File "Interface.py", line 205, in pegarRedeSalva
    self._setListStore(self.inputs, numTargets, True)
  File "Interface.py", line 383, in _setListStore
    pesos = self.net.layers[0].np['w']
AttributeError: 'NoneType' object has no attribute 'layers'
Traceback (most recent call last):
  File "Interface.py", line 205, in pegarRedeSalva
    self._setListStore(self.inputs, numTargets, True)
  File "Interface.py", line 383, in _setListStore
    pesos = self.net.layers[0].np['w']
AttributeError: 'NoneType' object has no attribute 'layers'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "Interface.py", line 233, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 233, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 233, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 269, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 84, in treinar
    lr=self.taxaAprendizado.get_value(),
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 325, in __call__
    target = np.asfarray(target)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 105, in asfarray
    return asarray(a, dtype=dtype)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 460, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 409, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "Interface.py", line 412, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 412, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
AttributeError: 'NoneType' object has no attribute 'sim'
Traceback (most recent call last):
  File "Interface.py", line 269, in aprender
    self.errors = tr.treinar("gdx")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 65, in treinar
    self.net.trainf = neurolab.train.train_gdx
AttributeError: 'NoneType' object has no attribute 'trainf'
Traceback (most recent call last):
  File "Interface.py", line 269, in aprender
    self.errors = tr.treinar("gdx")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 65, in treinar
    self.net.trainf = neurolab.train.train_gdx
AttributeError: 'NoneType' object has no attribute 'trainf'
Traceback (most recent call last):
  File "Interface.py", line 412, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
AttributeError: 'NoneType' object has no attribute 'sim'
Traceback (most recent call last):
  File "Interface.py", line 23, in <module>
    from gi.repository import vte
ImportError: cannot import name vte
Traceback (most recent call last):
  File "Interface.py", line 220, in pegarRedeSalva
    self.net = neurolab.load(dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 55, in load
    net = load(file)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 891, in load_persid
    self.append(self.persistent_load(pid))
AttributeError: Unpickler instance has no attribute 'persistent_load'
Traceback (most recent call last):
  File "Interface.py", line 220, in pegarRedeSalva
    self.net = neurolab.load(dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 55, in load
    net = load(file)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
KeyError: '#'
Traceback (most recent call last):
  File "Interface.py", line 424, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
AttributeError: 'NoneType' object has no attribute 'sim'
Traceback (most recent call last):
  File "Interface.py", line 218, in pegarRedeSalva
    self.net = neurolab.load(dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 55, in load
    net = load(file)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 891, in load_persid
    self.append(self.persistent_load(pid))
AttributeError: Unpickler instance has no attribute 'persistent_load'
Traceback (most recent call last):
  File "Interface.py", line 269, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 28, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 349, in __call__
    train(net, *args)
  File "/home/targueriano/Documents/TC_II/src/neurolab/train/spo.py", line 79, in __call__
    **self.kwargs)
TypeError: fmin_bfgs() got an unexpected keyword argument 'lr'
Traceback (most recent call last):
  File "Interface.py", line 272, in aprender
    self.errors = tr.treinar("gd")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 32, in treinar
    self.net.trainf = neurolab.train.train_gd
AttributeError: 'NoneType' object has no attribute 'trainf'
Traceback (most recent call last):
  File "Interface.py", line 284, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 79, in treinar
    self.net.trainf = neurolab.train.train_rprop
AttributeError: 'NoneType' object has no attribute 'trainf'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 55, in criarArquitetura
    pygame.draw.circle(screen,gray, (x,y*(aux+2)), tamNodo, 0)
NameError: global name 'screen' is not defined
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 42, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 322, in tratarEntrada
    novaf = self.extrair_dados(caminho)
  File "Interface.py", line 340, in extrair_dados
    data = get_data(caminho)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_ods/__init__.py", line 344, in get_data
    return read_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 311, in get_data
    data = load_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 176, in load_data
    filename))
NotImplementedError: Cannot read content of file type md from file /home/targueriano/neuroIFC/README.md
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 281, in aprender
    self.errors = tr.treinar("gdx")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 75, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 325, in __call__
    target = np.asfarray(target)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 105, in asfarray
    return asarray(a, dtype=dtype)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 460, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 218, in pegarRedeSalva
    self.net = neurolab.load(dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 55, in load
    net = load(file)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 891, in load_persid
    self.append(self.persistent_load(pid))
AttributeError: Unpickler instance has no attribute 'persistent_load'
Traceback (most recent call last):
  File "Interface.py", line 269, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 28, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 349, in __call__
    train(net, *args)
  File "/home/targueriano/Documents/TC_II/src/neurolab/train/spo.py", line 79, in __call__
    **self.kwargs)
TypeError: fmin_bfgs() got an unexpected keyword argument 'lr'
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 322, in tratarEntrada
    novaf = self.extrair_dados(caminho)
  File "Interface.py", line 340, in extrair_dados
    data = get_data(caminho)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_ods/__init__.py", line 344, in get_data
    return read_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 311, in get_data
    data = load_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 176, in load_data
    filename))
NotImplementedError: Cannot read content of file type png from file /home/targueriano/neuroIFC/neuroIFC.png
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 245, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 245, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 142, in sim
    assert input.shape[1] == self.ci
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 142, in sim
    assert input.shape[1] == self.ci
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
AttributeError: 'NoneType' object has no attribute 'sim'
Traceback (most recent call last):
  File "Interface.py", line 287, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 84, in treinar
    lr=self.taxaAprendizado.get_value(),
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 287, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 84, in treinar
    lr=self.taxaAprendizado.get_value(),
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 142, in sim
    assert input.shape[1] == self.ci
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 221, in pegarRedeSalva
    self.net = neurolab.load(dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 55, in load
    net = load(file)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 891, in load_persid
    self.append(self.persistent_load(pid))
AttributeError: Unpickler instance has no attribute 'persistent_load'
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 432, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 272, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 28, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 321, in __call__
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 245, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 434, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
AttributeError: 'NoneType' object has no attribute 'sim'
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 431, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 432, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 433, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 439, in simular
    print numTarget
NameError: global name 'numTarget' is not defined
Traceback (most recent call last):
  File "Interface.py", line 439, in simular
    print numTarget
NameError: global name 'numTarget' is not defined
Traceback (most recent call last):
  File "Interface.py", line 332, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 333, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 334, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 334, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 334, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 334, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 334, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 334, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/RNA.py", line 35, in criarRede
    net = nl.net.newff(self.intervaloEntrada, self.listaNeuronios, trans)
  File "/home/targueriano/Documents/TC_II/src/neurolab/net.py", line 91, in newff
    net = Net(minmax, net_co, layers, connect, train.train_bfgs, error.SSE())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 65, in __init__
    assert self.inp_minmax.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 253, in criarRede
    self._setListStore(self.inputs, numTargets, True)
  File "Interface.py", line 381, in _setListStore
    pesos = self.net.layers[0].np['w']
AttributeError: 'NoneType' object has no attribute 'layers'
Traceback (most recent call last):
  File "Interface.py", line 280, in aprender
    self.errors = tr.treinar("gdm")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 49, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 280, in aprender
    self.errors = tr.treinar("gdm")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 49, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 280, in aprender
    self.errors = tr.treinar("gdm")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 49, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 252, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 280, in aprender
    self.errors = tr.treinar("gdm")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 49, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 325, in __call__
    target = np.asfarray(target)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 105, in asfarray
    return asarray(a, dtype=dtype)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 460, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "Interface.py", line 275, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 25, in treinar
    self.errors = self.net.train(self.inputs, self.targets,
AttributeError: 'NoneType' object has no attribute 'train'
Traceback (most recent call last):
  File "Interface.py", line 405, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
AttributeError: 'NoneType' object has no attribute 'sim'
Traceback (most recent call last):
  File "Interface.py", line 275, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 28, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 349, in __call__
    train(net, *args)
  File "/home/targueriano/Documents/TC_II/src/neurolab/train/spo.py", line 79, in __call__
    **self.kwargs)
TypeError: fmin_bfgs() got an unexpected keyword argument 'lr'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/RNA.py", line 35, in criarRede
    net = nl.net.newff(self.intervaloEntrada, self.listaNeuronios, trans)
  File "/home/targueriano/Documents/TC_II/src/neurolab/net.py", line 91, in newff
    net = Net(minmax, net_co, layers, connect, train.train_bfgs, error.SSE())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 92, in __init__
    minmax[ni: ni + len(t)] = t
ValueError: could not broadcast input array from shape (0) into shape (0,2)
Traceback (most recent call last):
  File "Interface.py", line 254, in criarRede
    self._setListStore(self.inputs, numTargets, True)
  File "Interface.py", line 379, in _setListStore
    pesos = self.net.layers[0].np['w']
AttributeError: 'NoneType' object has no attribute 'layers'
Traceback (most recent call last):
  File "Interface.py", line 278, in aprender
    self.errors = tr.treinar("gd")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 38, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 249, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 249, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 249, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 249, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 276, in aprender
    self.errors = tr.treinar("delta")
  File "/media/sf_targueriano/Documents/TC_II/src/Treinamento.py", line 25, in treinar
    self.errors = self.net.train(self.inputs, self.targets,
AttributeError: 'NoneType' object has no attribute 'train'
Traceback (most recent call last):
  File "Interface.py", line 249, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 26, in <module>
    from pyexcel_ods import get_data
  File "/media/sf_targueriano/Documents/TC_II/src/pyexcel_ods/__init__.py", line 30, in <module>
    from pyexcel_io import (
ImportError: cannot import name SheetReaderBase
Traceback (most recent call last):
  File "/media/sf_targueriano/Documents/TC_II/src/RNA.py", line 35, in criarRede
    net = nl.net.newff(self.intervaloEntrada, self.listaNeuronios, trans)
  File "/media/sf_targueriano/Documents/TC_II/src/neurolab/net.py", line 91, in newff
    net = Net(minmax, net_co, layers, connect, train.train_bfgs, error.SSE())
  File "/media/sf_targueriano/Documents/TC_II/src/neurolab/core.py", line 65, in __init__
    assert self.inp_minmax.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 255, in criarRede
    self._setListStore(self.inputs, numTargets, True)
  File "Interface.py", line 385, in _setListStore
    pesos = self.net.layers[0].np['w']
AttributeError: 'NoneType' object has no attribute 'layers'
Traceback (most recent call last):
  File "Interface.py", line 254, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 255, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 255, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 250, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/targueriano/neuroIFC/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Desenho.py", line 45, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "Interface.py", line 294, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/neuroIFC/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 84, in treinar
    lr=self.taxaAprendizado.get_value(),
  File "/usr/local/lib/python2.7/dist-packages/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 288, in aprender
    self.errors = tr.treinar("gda")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 61, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 169, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 364, in __call__
    train(net, *args)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/train/gd.py", line 53, in __call__
    self.epochf(e, net, input, target)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 348, in epochf
    fig = plt.figure()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 435, in figure
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 98, in new_figure_manager_given_figure
    icon_img = Tk.PhotoImage(file=icon_fname)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3365, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3319, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
TclError: can't invoke "image" command: application has been destroyed
Traceback (most recent call last):
  File "Interface.py", line 291, in aprender
    self.errors = tr.treinar("gdx")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 75, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 169, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 364, in __call__
    train(net, *args)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/train/gd.py", line 53, in __call__
    self.epochf(e, net, input, target)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 348, in epochf
    fig = plt.figure()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 435, in figure
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 98, in new_figure_manager_given_figure
    icon_img = Tk.PhotoImage(file=icon_fname)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3365, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3319, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
TclError: can't invoke "image" command: application has been destroyed
Traceback (most recent call last):
  File "Interface.py", line 291, in aprender
    self.errors = tr.treinar("gdx")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 75, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 169, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 373, in __call__
    ani = animation.FuncAnimation(fig, animacao, fargs=[self.x,self.y],
NameError: global name 'fig' is not defined
Traceback (most recent call last):
  File "Interface.py", line 291, in aprender
    self.errors = tr.treinar("gdx")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 75, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 169, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 374, in __call__
    ani = animation.FuncAnimation(fig, self.animacao, fargs=[self.x,self.y],
NameError: global name 'fig' is not defined
Traceback (most recent call last):
  File "Interface.py", line 312, in aprender
    anima.Animacao(self.errors)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Animacao.py", line 23, in __init__
    ani = animation.FuncAnimation(fig, self.animacao, np.arange(0,epoca), interval = 700)
  File "/usr/lib/python2.7/dist-packages/matplotlib/animation.py", line 1052, in __init__
    TimedAnimation.__init__(self, fig, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/animation.py", line 898, in __init__
    *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/animation.py", line 576, in __init__
    self._init_draw()
  File "/usr/lib/python2.7/dist-packages/matplotlib/animation.py", line 1077, in _init_draw
    self._draw_frame(next(self.new_frame_seq()))
  File "/usr/lib/python2.7/dist-packages/matplotlib/animation.py", line 1091, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
TypeError: animacao() takes exactly 1 argument (2 given)
Traceback (most recent call last):
  File "Interface.py", line 312, in aprender
    anima.Animacao(self.errors)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Animacao.py", line 23, in __init__
    ani = animation.FuncAnimation(fig, self.animacao, np.arange(0,epoca), interval = 700)
  File "/usr/lib/python2.7/dist-packages/matplotlib/animation.py", line 1052, in __init__
    TimedAnimation.__init__(self, fig, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/animation.py", line 898, in __init__
    *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/animation.py", line 576, in __init__
    self._init_draw()
  File "/usr/lib/python2.7/dist-packages/matplotlib/animation.py", line 1077, in _init_draw
    self._draw_frame(next(self.new_frame_seq()))
  File "/usr/lib/python2.7/dist-packages/matplotlib/animation.py", line 1091, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
TypeError: animacao() takes exactly 1 argument (2 given)
Traceback (most recent call last):
  File "Interface.py", line 257, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 311, in aprender
    if self.switchAnimacao.active():
AttributeError: 'Switch' object has no attribute 'active'
Traceback (most recent call last):
  File "Interface.py", line 311, in aprender
    if self.switchAnimacao.active():
AttributeError: 'Switch' object has no attribute 'active'
Traceback (most recent call last):
  File "Interface.py", line 312, in aprender
    a = anima.Animacao(self.errors)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Animacao.py", line 22, in __init__
    plt.show()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 155, in show
    return _show(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 184, in __call__
    self.mainloop()
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 71, in mainloop
    Tk.mainloop()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 413, in mainloop
    _default_root.tk.mainloop(n)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1537, in __call__
    raise SystemExit, msg
SystemExit
Traceback (most recent call last):
  File "Interface.py", line 312, in aprender
    a = anima.Animacao(self.errors)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Animacao.py", line 22, in __init__
    plt.show()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 155, in show
    return _show(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 184, in __call__
    self.mainloop()
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 71, in mainloop
    Tk.mainloop()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 413, in mainloop
    _default_root.tk.mainloop(n)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1537, in __call__
    raise SystemExit, msg
SystemExit
Traceback (most recent call last):
  File "Interface.py", line 312, in aprender
    a = anima.Animacao(self.errors)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Animacao.py", line 16, in __init__
    plt.ylim(erro*2)
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 1519, in ylim
    ret = ax.set_ylim(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 2773, in set_ylim
    bottom, top = bottom
ValueError: too many values to unpack
Traceback (most recent call last):
  File "Interface.py", line 312, in aprender
    a = anima.Animacao(self.errors)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Animacao.py", line 14, in __init__
    fig = plt.figure()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 435, in figure
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 98, in new_figure_manager_given_figure
    icon_img = Tk.PhotoImage(file=icon_fname)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3365, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3319, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
RuntimeError: main thread is not in main loop
Traceback (most recent call last):
  File "Interface.py", line 257, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 314, in aprender
    self._animarErro()
  File "Interface.py", line 330, in _animarErro
    a = anima.Animacao(self.errors)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Animacao.py", line 18, in __init__
    print intervalo
NameError: global name 'intervalo' is not defined
Traceback (most recent call last):
  File "Interface.py", line 314, in aprender
    self._animarErro()
  File "Interface.py", line 333, in _animarErro
    a.exit()
AttributeError: 'Animacao' object has no attribute 'exit'
Traceback (most recent call last):
  File "Interface.py", line 314, in aprender
    self._animarErro()
  File "Interface.py", line 333, in _animarErro
    a.exit()
AttributeError: 'Animacao' object has no attribute 'exit'
Traceback (most recent call last):
  File "Interface.py", line 253, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 295, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 84, in treinar
    lr=self.taxaAprendizado.get_value(),
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 169, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 326, in __call__
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 280, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 28, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 169, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 356, in __call__
    train(net, *args)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/train/spo.py", line 79, in __call__
    **self.kwargs)
TypeError: fmin_bfgs() got an unexpected keyword argument 'lr'
Traceback (most recent call last):
  File "Interface.py", line 289, in aprender
    self.errors = tr.treinar("gda")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 61, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 169, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 326, in __call__
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 280, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 25, in treinar
    self.errors = self.net.train(self.inputs, self.targets,
AttributeError: 'NoneType' object has no attribute 'train'
Traceback (most recent call last):
  File "Interface.py", line 253, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 253, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 258, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 253, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 292, in aprender
    self.errors = tr.treinar("gdx")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 75, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 169, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 326, in __call__
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 345, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 84, in treinar
    lr=self.taxaAprendizado.get_value(),
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 169, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 326, in __call__
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 356, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 84, in treinar
    lr=self.taxaAprendizado.get_value(),
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 169, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 326, in __call__
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 309, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 309, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 356, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 84, in treinar
    lr=self.taxaAprendizado.get_value(),
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 169, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 327, in __call__
    assert input.shape[1] == net.ci
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 309, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 356, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Projects/neuroIFC/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 84, in treinar
    lr=self.taxaAprendizado.get_value(),
  File "/usr/lib/python2.7/site-packages/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/neurolab/core.py", line 321, in __call__
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 318, in criarRede
    for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 356, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Projects/neuroIFC/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 84, in treinar
    lr=self.taxaAprendizado.get_value(),
  File "/usr/lib/python2.7/site-packages/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/neurolab/core.py", line 325, in __call__
    target = np.asfarray(target)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/type_check.py", line 105, in asfarray
    return asarray(a, dtype=dtype)
  File "/usr/lib64/python2.7/site-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "Interface.py", line 318, in criarRede
    for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 418, in tratarEntrada
    self.targets.append(novaf[i][-1])
AttributeError: 'NoneType' object has no attribute 'append'
Traceback (most recent call last):
  File "Interface.py", line 418, in tratarEntrada
    self.targets.append(novaf[i][-1])
AttributeError: 'NoneType' object has no attribute 'append'
Traceback (most recent call last):
  File "Interface.py", line 309, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "Interface.py", line 418, in tratarEntrada
    self.targets.append(novaf[i][-1])
AttributeError: 'NoneType' object has no attribute 'append'
Traceback (most recent call last):
  File "Interface.py", line 309, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "Interface.py", line 353, in aprender
    self.errors = tr.treinar("gdx")
  File "/home/targueriano/Projects/neuroIFC/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 65, in treinar
    self.net.trainf = neurolab.train.train_gdx
AttributeError: 'NoneType' object has no attribute 'trainf'
Traceback (most recent call last):
  File "Interface.py", line 434, in extrair_dados
    data = get_data(caminho)
  File "/home/targueriano/Projects/neuroIFC/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/pyexcel_ods/__init__.py", line 344, in get_data
    return read_data(afile, file_type=file_type, **keywords)
  File "/home/targueriano/Projects/neuroIFC/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/pyexcel_io/__init__.py", line 311, in get_data
    data = load_data(afile, file_type=file_type, **keywords)
  File "/home/targueriano/Projects/neuroIFC/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/pyexcel_io/__init__.py", line 176, in load_data
    filename))
NotImplementedError: Cannot read content of file type net from file /home/targueriano/Projects/neuroIFC/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/exemplos/SLP_simple.net
Traceback (most recent call last):
  File "Interface.py", line 340, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 28, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 169, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 356, in __call__
    train(net, *args)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/train/spo.py", line 79, in __call__
    **self.kwargs)
TypeError: fmin_bfgs() got an unexpected keyword argument 'lr'
Traceback (most recent call last):
  File "Interface.py", line 308, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 355, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 79, in treinar
    self.net.trainf = neurolab.train.train_rprop
AttributeError: 'NoneType' object has no attribute 'trainf'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Desenho.py", line 41, in criarArquitetura
    lista_str = self.lista.get_text().split(",")
AttributeError: 'str' object has no attribute 'get_text'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Desenho.py", line 41, in criarArquitetura
    lista_str = self.lista.get_text().split(",")
AttributeError: 'str' object has no attribute 'get_text'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Desenho.py", line 41, in criarArquitetura
    lista_str = self.lista.get_text().split(",")
AttributeError: 'str' object has no attribute 'get_text'
Traceback (most recent call last):
  File "Interface.py", line 283, in salvar
    self.net.save(nome)
AttributeError: 'NoneType' object has no attribute 'save'
Traceback (most recent call last):
  File "Interface.py", line 466, in extrair_dados
    data = get_data(caminho)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_ods/__init__.py", line 344, in get_data
    return read_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 311, in get_data
    data = load_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 176, in load_data
    filename))
NotImplementedError: Cannot read content of file type mkv from file /home/targueriano/Videos/John.Wick.2014.1080p.WEB-DL.DD5.1.H264-RARBG/John.Wick.2014.1080p.WEB-DL.DD5.1.H264-RARBG.mkv
Traceback (most recent call last):
  File "Interface.py", line 406, in aprender
    for i in xrange(self.show.get_value_as_int()-1, len(self.errors),
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "Interface.py", line 358, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 390, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/Treinamento.py", line 28, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 169, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/core.py", line 356, in __call__
    train(net, *args)
  File "/home/targueriano/Documents/TC_II/neuro-ifc_1.0.16_amd64/usr/local/neuro-ifc/src/neurolab/train/spo.py", line 79, in __call__
    **self.kwargs)
TypeError: fmin_bfgs() got an unexpected keyword argument 'lr'
