################################################################
################        2675 linhas de codigo    ###############
################################################################

Traceback (most recent call last):
  File "Interface.py", line 250, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 28, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 182, in salvar
    self.statusFile.push(contexto,str(dialog.get_filename()))
NameError: global name 'dialog' is not defined
Traceback (most recent call last):
  File "Interface.py", line 175, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 175, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 175, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.statusFile.push(contexto,str(self.dialog.get_filename()))
AttributeError: 'NoneType' object has no attribute 'get_filename'
Traceback (most recent call last):
  File "Interface.py", line 174, in salvar
    self.dialog.destroy()
AttributeError: 'NoneType' object has no attribute 'destroy'
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 177, in salvar
    self.net.save(self.dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 186, in save
    tool.save(self, fname)
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 62, in save
    with open(fname, 'wb') as file:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "Interface.py", line 401, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "Interface.py", line 401, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 270, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 79, in treinar
    self.net.trainf = neurolab.train.train_rprop
AttributeError: 'NoneType' object has no attribute 'trainf'
Traceback (most recent call last):
  File "Interface.py", line 228, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 410, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
AttributeError: 'NoneType' object has no attribute 'sim'
Traceback (most recent call last):
  File "Interface.py", line 228, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 309, in tratarEntrada
    novaf = self.extrair_dados(caminho)
  File "Interface.py", line 327, in extrair_dados
    data = get_data(caminho)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_ods/__init__.py", line 344, in get_data
    return read_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 311, in get_data
    data = load_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 176, in load_data
    filename))
NotImplementedError: Cannot read content of file type png from file /home/targueriano/neuroIFC/neuro.png
Traceback (most recent call last):
  File "Interface.py", line 309, in tratarEntrada
    novaf = self.extrair_dados(caminho)
  File "Interface.py", line 327, in extrair_dados
    data = get_data(caminho)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_ods/__init__.py", line 344, in get_data
    return read_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 311, in get_data
    data = load_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 176, in load_data
    filename))
NotImplementedError: Cannot read content of file type png from file /home/targueriano/neuroIFC/neuro.png
Traceback (most recent call last):
  File "Interface.py", line 227, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 254, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 25, in treinar
    self.errors = self.net.train(self.inputs, self.targets,
AttributeError: 'NoneType' object has no attribute 'train'
Traceback (most recent call last):
  File "Interface.py", line 205, in pegarRedeSalva
    self._setListStore(self.inputs, numTargets, True)
  File "Interface.py", line 383, in _setListStore
    pesos = self.net.layers[0].np['w']
AttributeError: 'NoneType' object has no attribute 'layers'
Traceback (most recent call last):
  File "Interface.py", line 205, in pegarRedeSalva
    self._setListStore(self.inputs, numTargets, True)
  File "Interface.py", line 383, in _setListStore
    pesos = self.net.layers[0].np['w']
AttributeError: 'NoneType' object has no attribute 'layers'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "Interface.py", line 233, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 233, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 233, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 269, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 84, in treinar
    lr=self.taxaAprendizado.get_value(),
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 325, in __call__
    target = np.asfarray(target)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 105, in asfarray
    return asarray(a, dtype=dtype)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 460, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 232, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 409, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "Interface.py", line 412, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 412, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
AttributeError: 'NoneType' object has no attribute 'sim'
Traceback (most recent call last):
  File "Interface.py", line 269, in aprender
    self.errors = tr.treinar("gdx")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 65, in treinar
    self.net.trainf = neurolab.train.train_gdx
AttributeError: 'NoneType' object has no attribute 'trainf'
Traceback (most recent call last):
  File "Interface.py", line 269, in aprender
    self.errors = tr.treinar("gdx")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 65, in treinar
    self.net.trainf = neurolab.train.train_gdx
AttributeError: 'NoneType' object has no attribute 'trainf'
Traceback (most recent call last):
  File "Interface.py", line 412, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
AttributeError: 'NoneType' object has no attribute 'sim'
Traceback (most recent call last):
  File "Interface.py", line 23, in <module>
    from gi.repository import vte
ImportError: cannot import name vte
Traceback (most recent call last):
  File "Interface.py", line 220, in pegarRedeSalva
    self.net = neurolab.load(dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 55, in load
    net = load(file)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 891, in load_persid
    self.append(self.persistent_load(pid))
AttributeError: Unpickler instance has no attribute 'persistent_load'
Traceback (most recent call last):
  File "Interface.py", line 220, in pegarRedeSalva
    self.net = neurolab.load(dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 55, in load
    net = load(file)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
KeyError: '#'
Traceback (most recent call last):
  File "Interface.py", line 424, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
AttributeError: 'NoneType' object has no attribute 'sim'
Traceback (most recent call last):
  File "Interface.py", line 218, in pegarRedeSalva
    self.net = neurolab.load(dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 55, in load
    net = load(file)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 891, in load_persid
    self.append(self.persistent_load(pid))
AttributeError: Unpickler instance has no attribute 'persistent_load'
Traceback (most recent call last):
  File "Interface.py", line 269, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 28, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 349, in __call__
    train(net, *args)
  File "/home/targueriano/Documents/TC_II/src/neurolab/train/spo.py", line 79, in __call__
    **self.kwargs)
TypeError: fmin_bfgs() got an unexpected keyword argument 'lr'
Traceback (most recent call last):
  File "Interface.py", line 272, in aprender
    self.errors = tr.treinar("gd")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 32, in treinar
    self.net.trainf = neurolab.train.train_gd
AttributeError: 'NoneType' object has no attribute 'trainf'
Traceback (most recent call last):
  File "Interface.py", line 284, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 79, in treinar
    self.net.trainf = neurolab.train.train_rprop
AttributeError: 'NoneType' object has no attribute 'trainf'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 55, in criarArquitetura
    pygame.draw.circle(screen,gray, (x,y*(aux+2)), tamNodo, 0)
NameError: global name 'screen' is not defined
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 43, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/Desenho.py", line 42, in criarArquitetura
    sys.atexit()
AttributeError: 'module' object has no attribute 'atexit'
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 322, in tratarEntrada
    novaf = self.extrair_dados(caminho)
  File "Interface.py", line 340, in extrair_dados
    data = get_data(caminho)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_ods/__init__.py", line 344, in get_data
    return read_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 311, in get_data
    data = load_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 176, in load_data
    filename))
NotImplementedError: Cannot read content of file type md from file /home/targueriano/neuroIFC/README.md
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 281, in aprender
    self.errors = tr.treinar("gdx")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 75, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 325, in __call__
    target = np.asfarray(target)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 105, in asfarray
    return asarray(a, dtype=dtype)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 460, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 218, in pegarRedeSalva
    self.net = neurolab.load(dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 55, in load
    net = load(file)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 891, in load_persid
    self.append(self.persistent_load(pid))
AttributeError: Unpickler instance has no attribute 'persistent_load'
Traceback (most recent call last):
  File "Interface.py", line 269, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 28, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 349, in __call__
    train(net, *args)
  File "/home/targueriano/Documents/TC_II/src/neurolab/train/spo.py", line 79, in __call__
    **self.kwargs)
TypeError: fmin_bfgs() got an unexpected keyword argument 'lr'
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 322, in tratarEntrada
    novaf = self.extrair_dados(caminho)
  File "Interface.py", line 340, in extrair_dados
    data = get_data(caminho)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_ods/__init__.py", line 344, in get_data
    return read_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 311, in get_data
    data = load_data(afile, file_type=file_type, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/pyexcel_io/__init__.py", line 176, in load_data
    filename))
NotImplementedError: Cannot read content of file type png from file /home/targueriano/neuroIFC/neuroIFC.png
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 245, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 245, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 142, in sim
    assert input.shape[1] == self.ci
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 142, in sim
    assert input.shape[1] == self.ci
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
AttributeError: 'NoneType' object has no attribute 'sim'
Traceback (most recent call last):
  File "Interface.py", line 287, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 84, in treinar
    lr=self.taxaAprendizado.get_value(),
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 287, in aprender
    self.errors = tr.treinar("rprop")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 84, in treinar
    lr=self.taxaAprendizado.get_value(),
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 142, in sim
    assert input.shape[1] == self.ci
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 221, in pegarRedeSalva
    self.net = neurolab.load(dialog.get_filename())
  File "/home/targueriano/Documents/TC_II/src/neurolab/tool.py", line 55, in load
    net = load(file)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 891, in load_persid
    self.append(self.persistent_load(pid))
AttributeError: Unpickler instance has no attribute 'persistent_load'
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 432, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 272, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 28, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 321, in __call__
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 245, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 428, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 434, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
AttributeError: 'NoneType' object has no attribute 'sim'
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 430, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 431, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 432, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 433, in simular
    self.saidaSimulador = self.net.sim(self.inputSimulador)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 141, in sim
    assert input.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 439, in simular
    print numTarget
NameError: global name 'numTarget' is not defined
Traceback (most recent call last):
  File "Interface.py", line 439, in simular
    print numTarget
NameError: global name 'numTarget' is not defined
Traceback (most recent call last):
  File "Interface.py", line 332, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 333, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 334, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 334, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 334, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 334, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 334, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 334, in tratarEntrada
    self.targets.append(novaf[i][-1])
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 247, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/RNA.py", line 35, in criarRede
    net = nl.net.newff(self.intervaloEntrada, self.listaNeuronios, trans)
  File "/home/targueriano/Documents/TC_II/src/neurolab/net.py", line 91, in newff
    net = Net(minmax, net_co, layers, connect, train.train_bfgs, error.SSE())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 65, in __init__
    assert self.inp_minmax.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 253, in criarRede
    self._setListStore(self.inputs, numTargets, True)
  File "Interface.py", line 381, in _setListStore
    pesos = self.net.layers[0].np['w']
AttributeError: 'NoneType' object has no attribute 'layers'
Traceback (most recent call last):
  File "Interface.py", line 280, in aprender
    self.errors = tr.treinar("gdm")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 49, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 280, in aprender
    self.errors = tr.treinar("gdm")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 49, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 280, in aprender
    self.errors = tr.treinar("gdm")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 49, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 252, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 280, in aprender
    self.errors = tr.treinar("gdm")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 49, in treinar
    rr=self.taxaRegularizacao.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 325, in __call__
    target = np.asfarray(target)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 105, in asfarray
    return asarray(a, dtype=dtype)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 460, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
Traceback (most recent call last):
  File "Interface.py", line 275, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 25, in treinar
    self.errors = self.net.train(self.inputs, self.targets,
AttributeError: 'NoneType' object has no attribute 'train'
Traceback (most recent call last):
  File "Interface.py", line 405, in simular
    self.saidaSimulador = self.net.sim(self.inputs)
AttributeError: 'NoneType' object has no attribute 'sim'
Traceback (most recent call last):
  File "Interface.py", line 275, in aprender
    self.errors = tr.treinar("delta")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 28, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 349, in __call__
    train(net, *args)
  File "/home/targueriano/Documents/TC_II/src/neurolab/train/spo.py", line 79, in __call__
    **self.kwargs)
TypeError: fmin_bfgs() got an unexpected keyword argument 'lr'
Traceback (most recent call last):
  File "/home/targueriano/Documents/TC_II/src/RNA.py", line 35, in criarRede
    net = nl.net.newff(self.intervaloEntrada, self.listaNeuronios, trans)
  File "/home/targueriano/Documents/TC_II/src/neurolab/net.py", line 91, in newff
    net = Net(minmax, net_co, layers, connect, train.train_bfgs, error.SSE())
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 92, in __init__
    minmax[ni: ni + len(t)] = t
ValueError: could not broadcast input array from shape (0) into shape (0,2)
Traceback (most recent call last):
  File "Interface.py", line 254, in criarRede
    self._setListStore(self.inputs, numTargets, True)
  File "Interface.py", line 379, in _setListStore
    pesos = self.net.layers[0].np['w']
AttributeError: 'NoneType' object has no attribute 'layers'
Traceback (most recent call last):
  File "Interface.py", line 278, in aprender
    self.errors = tr.treinar("gd")
  File "/home/targueriano/Documents/TC_II/src/Treinamento.py", line 38, in treinar
    lr=self.taxaAprendizado.get_value()
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 165, in train
    return self.trainf(self, *args, **kwargs)
  File "/home/targueriano/Documents/TC_II/src/neurolab/core.py", line 327, in __call__
    assert target.shape[1] == net.co
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 249, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 249, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 249, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 249, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 276, in aprender
    self.errors = tr.treinar("delta")
  File "/media/sf_targueriano/Documents/TC_II/src/Treinamento.py", line 25, in treinar
    self.errors = self.net.train(self.inputs, self.targets,
AttributeError: 'NoneType' object has no attribute 'train'
Traceback (most recent call last):
  File "Interface.py", line 249, in criarRede
    intervalo = [[-100, 100] for i in xrange(len(self.inputs[0]))]
IndexError: list index out of range
Traceback (most recent call last):
  File "Interface.py", line 26, in <module>
    from pyexcel_ods import get_data
  File "/media/sf_targueriano/Documents/TC_II/src/pyexcel_ods/__init__.py", line 30, in <module>
    from pyexcel_io import (
ImportError: cannot import name SheetReaderBase
Traceback (most recent call last):
  File "/media/sf_targueriano/Documents/TC_II/src/RNA.py", line 35, in criarRede
    net = nl.net.newff(self.intervaloEntrada, self.listaNeuronios, trans)
  File "/media/sf_targueriano/Documents/TC_II/src/neurolab/net.py", line 91, in newff
    net = Net(minmax, net_co, layers, connect, train.train_bfgs, error.SSE())
  File "/media/sf_targueriano/Documents/TC_II/src/neurolab/core.py", line 65, in __init__
    assert self.inp_minmax.ndim == 2
AssertionError
Traceback (most recent call last):
  File "Interface.py", line 255, in criarRede
    self._setListStore(self.inputs, numTargets, True)
  File "Interface.py", line 385, in _setListStore
    pesos = self.net.layers[0].np['w']
AttributeError: 'NoneType' object has no attribute 'layers'
Traceback (most recent call last):
  File "Interface.py", line 254, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 255, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
Traceback (most recent call last):
  File "Interface.py", line 255, in criarRede
    numTargets = [float(self.targets[i][j]) for i in xrange(len(self.targets)) for j in xrange(1)]
TypeError: float() argument must be a string or a number
